//==============================================================
//
// SAMPLE SOURCE CODE - SUBJECT TO THE TERMS OF SAMPLE CODE LICENSE AGREEMENT,
// http://software.intel.com/en-us/articles/intel-sample-source-code-license-agreement/
//
// Copyright 2016 Intel Corporation
//
// THIS FILE IS PROVIDED "AS IS" WITH NO WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE, NON-INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS.
//
// =============================================================

//
// QuickDemo.h
// This file is part of the QuickSort demonstration of Intel(R) Cilk(TM) Plus.
//
// This file declares CQuickDemoApp, a CWinApp-derived class.  It's basically
// boilerplate code generated by Visual Studio 2005.
//

#pragma once

#ifndef __AFXWIN_H__
	#error "include 'stdafx.h' before including this file for PCH"
#endif

#include "resource.h"		// main symbols


// CQuickDemoApp:
// See QuickDemo.cpp for the implementation of this class
//

class CQuickDemoApp : public CWinApp
{
public:
	CQuickDemoApp();

// Overrides
    public:
	virtual BOOL InitInstance();
    	virtual int ExitInstance(); // return app exit code

// Implementation

protected:
	DECLARE_MESSAGE_MAP()

};

extern CQuickDemoApp theApp;